version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: cinema
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: on-failure
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: cinema@project.pet
      PGADMIN_DEFAULT_PASSWORD: 1111
    volumes:
      - ./servers.json:/pgadmin4/servers.json
